version: "3"

services:
  MySql_Dev:
    image: mysql:8.0.22
    container_name: MySql_Dev
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demo

  MySql_Test:
    image: mysql:8.0.22
    container_name: MySql_Test
    ports:
      - 3334:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test