spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3333/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  flyway:
    enabled: true
    encoding: utf-8
    url: jdbc:mysql://localhost:3333
    schemas: demo
    user: root
    password: 123456
